version: '3'
services:
  # api:
  #   build: .
  #   command: npm run dev
  #   volumes:
  #     - .:/app/
  #     - /app/node_modules
  #   ports:
  #     - '8000:8000'
  #   depends_on:
  #     - postgres
  #   env_file:
  #     - .env.dev
  postgres:
    image: 'postgres:latest'
    ports:
      - 5432:5432
    env_file:
      - .env.db
    volumes:
      - ./db-data/:/var/lib/postgresql/data/
volumes:
  postgres:
    driver: local
