version: '3'
services:
  app:
    image: 'node:latest'
    build: .
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - postgres
    links:
      - postgres

  postgres:
    image: 'postgres:latest'
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - ./db-data/:/var/lib/postgresql/data/
