version: '3'
services:
  api:
    build: .
    command: npm run dev
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - '8000:8000'
    depends_on:
      - postgres
    env_file:
      - .env
  postgres:
    image: 'postgres:latest'
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - ./db-data/:/var/lib/postgresql/data/
volumes:
  postgres:
    driver: local
