export default {
  colegiado_delete_vote: 'all',
  colegiado_update_vote: 'all',
  comentario_create: 'all',
  comentario_delete: 'all',
  colegiado_comments_read: 'all',
  comentario_read: 'all',
  comentario_update: 'all',
  formulario_create: 'all',
  formulario_delete: 'all',
  formulario_read: 'all',
  formulario_update: 'all',
  procedimento_create: 'all',
  procedimento_read: 'all',
  procedimento_update: 'all',
  procedimento_delete: 'all',
  procedimento_homologate: 'all',
  procedimento_review: 'all',
  tipo_procedimento_create: 'all',
  tipo_procedimento_delete: 'all',
  tipo_procedimento_read: 'all',
  tipo_procedimento_update: 'all',
  actor_create: 'all',
  actor_delete: 'all',
  actor_read: 'all',
  actor_update: 'all'
}
