export default {
  colegiado_delete_vote: 'owned',
  colegiado_update_vote: 'owned',
  comentario_create: 'owned',
  comentario_delete: 'owned',
  colegiado_comments_read: 'owned',
  comentario_read: 'owned',
  comentario_update: 'owned',
  formulario_create: 'owned',
  formulario_delete: 'owned',
  formulario_read: 'all',
  formulario_update: 'owned',
  procedimento_create: 'owned',
  procedimento_read: 'owned',
  procedimento_actor_read: 'all',
  procedimento_update: 'owned',
  procedimento_delete: 'owned',
  procedimento_homologate: 'owned',
  procedimento_review: 'owned',
  tipo_procedimento_create: 'owned',
  tipo_procedimento_delete: 'owned',
  tipo_procedimento_read: 'all',
  tipo_procedimento_update: 'owned'
}
